# Generated by Django 4.2.7 on 2025-09-04 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='CO code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='NOMBRE CO', max_length=200)),
                ('branch_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('headquarters_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('rtm_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('center_type', models.CharField(max_length=100)),
                ('regional', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('operation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='ACTIVO', max_length=50)),
                ('cameras', models.CharField(blank=True, max_length=200, null=True)),
                ('rtm_schedule', models.TextField(blank=True, null=True)),
                ('ac_schedule', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operational_centers',
            },
        ),
    ]
